name: Check deps for vulnerabilities

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clojure-tools
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: latest

    - name: Install clojure-nvd
      run: |
        clojure -Ttools install nvd-clojure/nvd-clojure '{:mvn/version "RELEASE"}' :as nvd

    - name: Check dependencies for CVEs
      run: |
        clojure -J-Dclojure.main.report=stderr -Tnvd nvd.task/check :classpath "\"$(lein classpath)\"" :config-filename \"".nvd-config.json\""
