name: Check deps for vulnerabilities

on:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: NVD clojure
      uses: jomco/nvd-clojure-action@v2
