name: Run tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache lein project dependencies
      uses: actions/cache@v3
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-clojure-${{ hashFiles('**/project.clj') }}"

    - name: Run linters
      run: lein lint

    - name: Run tests
      run: lein test

    - name: Run compile
      run: lein uberjar

  deps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache lein project dependencies
      uses: actions/cache@v3
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-clojure-${{ hashFiles('**/project.clj') }}"

    - name: Check dependency freshness
      run: lein check-deps

    - name: NVD clojure
      uses: jomco/nvd-clojure-action@v0

  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run docker build
      run: docker build .
