name: Run tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache lein project dependencies
      uses: actions/cache@v3
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-clojure-${{ hashFiles('**/project.clj') }}"

    - name: Run linters
      run: lein lint

    - name: Run tests
      run: lein test

    - name: Run compile
      run: lein uberjar

  deps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache lein project dependencies
      uses: actions/cache@v3
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-clojure-${{ hashFiles('**/project.clj') }}"

    - name: Check dependency freshness
      run: lein check-deps

    - name: Install clojure-tools
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: latest

    - name: Install clojure-nvd
      run: |
        clojure -Ttools install nvd-clojure/nvd-clojure '{:mvn/version "RELEASE"}' :as nvd

    - name: Check dependencies for CVEs
      run: |
        clojure -J-Dclojure.main.report=stderr -Tnvd nvd.task/check :classpath "\"$(lein classpath)\"" :config-filename "\".nvd-config.json\""

  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run docker build
      run: docker build .
